set_property PACKAGE_PIN G22 [get_ports a]
set_property PACKAGE_PIN D22 [get_ports b]
set_property PACKAGE_PIN M22 [get_ports out]
set_property PACKAGE_PIN B22 [get_ports sel]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports out]
set_property IOSTANDARD LVCMOS33 [get_ports sel]
